from logic_utils import check_guess

"""The first three tests where failing because check_guess was comparing the tuple directly
against a string. I asked Claude to suggest a fix and I reviewed and approved it."""
def test_winning_guess():
    # If the secret is 50 and guess is 50, it should be a win
    outcome, _ = check_guess(50, 50)
    assert outcome == "Win"

def test_guess_too_high():
    # If secret is 50 and guess is 60, hint should be "Too High"
    outcome, _ = check_guess(60, 50)
    assert outcome == "Too High"

def test_guess_too_low():
    # If secret is 50 and guess is 40, hint should be "Too Low"
    outcome, _ = check_guess(40, 50)
    assert outcome == "Too Low"

#Pytest generated by Claude to test TOO HIGH input against string secret.
def test_guess_too_high_with_string_secret():
    # Regression test for the high/low bug: app.py sometimes passes the
    # secret as a string (e.g. "9") instead of an int. A naive lexical
    # string comparison of "100" vs "9" says "100" < "9" (wrong), while
    # the correct numeric comparison says 100 > 9, i.e. "Too High".
    outcome, _ = check_guess(100, "9")
    assert outcome == "Too High"

#Pytest generated by Claude to test TOO LOW against string secret.
def test_guess_too_low_with_string_secret():
    # Same bug, opposite direction: lexical "5" vs "90" says "5" > "90"
    # (wrong), while numerically 5 < 90, i.e. "Too Low".
    outcome, _ = check_guess(5, "90")
    assert outcome == "Too Low"
